# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mm-versionable}
  s.version = "0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dhruva Sagar"]
  s.date = %q{2010-11-26}
  s.description = %q{A MongoMapper extension that enables document versionable}
  s.email = %q{dhruva.sagar@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "config.ru",
    "lib/versionable.rb",
    "lib/versionable/models/version.rb",
    "lib/versionable/plugins/versionable.rb",
    "lib/versionable/version.rb",
    "mm-versionable.gemspec",
    "test/config/config.rb",
    "test/config/database.yml",
    "test/models/post.rb",
    "test/models/user.rb",
    "test/performance/read_write.rb",
    "test/test_helper.rb",
    "test/unit/test_versioning.rb"
  ]
  s.homepage = %q{https://github.com/artha42/mm-versionable/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A MongoMapper extension for document versioning}
  s.test_files = [
    "test/config/config.rb",
    "test/models/post.rb",
    "test/models/user.rb",
    "test/performance/read_write.rb",
    "test/test_helper.rb",
    "test/unit/test_versioning.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<differ>, [">= 0"])
      s.add_runtime_dependency(%q<mongo_mapper>, [">= 0"])
    else
      s.add_dependency(%q<differ>, [">= 0"])
      s.add_dependency(%q<mongo_mapper>, [">= 0"])
    end
  else
    s.add_dependency(%q<differ>, [">= 0"])
    s.add_dependency(%q<mongo_mapper>, [">= 0"])
  end
end

